# .github/workflows/main.yml
name: Run ML Model Training

on:
  push:
    branches:
      - kernelridge # Trigger workflow on push to this branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run training and evaluation for both models
      run: |
        echo "--- Running Decision Tree Model ---"
        python train.py
        echo "--- Running Kernel Ridge Model ---"
        python train2.py
